In [22]:
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [2]:
path = '/home/jan/Documents/EPFL/project_2/data/input_datasets/CAFI_drivers.csv'
df = pd.read_csv(path)

In [3]:
df

,PLOTID,CEO_PLOTID,LON,LAT,ISO,CEO_Ref_Code,Ref_FNF,Ref_LCover,Ref_ChangeType,Ref_ChangeYear,...,Ref_InfraR,Ref_Urb,Ref_ArtAg,Ref_IndAg,Ref_ArtFor,Ref_IndFor,Ref_ArtMine,Ref_IndMine,Ref_Other,DriverGroup
0,10,1.0,29.542131,-0.900247,COD,16,0,16,NF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,20,2.0,8.943582,-0.859283,GAB,14,0,14,NF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,39,3.0,10.094054,6.326790,CMR,12,1,12,Stable,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,67,4.0,11.045101,-3.578214,GAB,1,1,1,Stable,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,98,5.0,16.671070,3.367470,COG,1,1,1,Stable,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12255,359840,11870.0,25.367391,-9.648041,COD,215,1,4,Def,2016.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,Rural Complex
12256,359846,11871.0,11.735546,5.495399,CMR,15,0,15,NF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
12257,359885,11872.0,25.603468,-9.521648,COD,206,1,2,Def,2017.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,Rural Complex
12258,359924,11873.0,22.431517,2.643068,COD,16,0,16,NF,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
12259,359957,11874.0,28.749009,-1.880398,COD,207,1,2,Def,2018.0,...,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,Rural Complex

In [6]:
# Convert LON and LAT to a geometry column
geometry = [Point(xy) for xy in zip(df.LON, df.LAT)]

# Create a GeoDataFrame
gdf = gpd.GeoDataFrame(df, geometry=geometry)

In [8]:
gdf.columns

Index(['PLOTID', 'CEO_PLOTID', 'LON', 'LAT', 'ISO', 'CEO_Ref_Code', 'Ref_FNF',
       'Ref_LCover', 'Ref_ChangeType', 'Ref_ChangeYear', 'countDrivers',
       'Ref_InfraR', 'Ref_Urb', 'Ref_ArtAg', 'Ref_IndAg', 'Ref_ArtFor',
       'Ref_IndFor', 'Ref_ArtMine', 'Ref_IndMine', 'Ref_Other', 'DriverGroup',
       'geometry'],
      dtype='object')

In [16]:
gdf_valid = gdf.loc[gdf.DriverGroup != '0'].reset_index(drop=True)

In [23]:
np.unique(gdf_valid.DriverGroup, return_counts=True)

(array(['Artisanal Forestry', 'Artisanal Mine', 'Development',
        'Industrial Agriculture', 'Industrial Forestry',
        'Industrial Forestry and Agriculture', 'Industrial Mine',
        'Infrastructure Agriculture', 'Other', 'Rural Complex'],
       dtype=object),
 array([ 187,   37,   56,  253,  223,   84,   59,  173,   68, 2671]))

In [ ]:
'''
filter:
"countDrivers" = 1  AND "Ref_ArtAg"  = 1

results in 561 items, but they seem like quite clean examples of shifting agriculture
plus approx. 200 more of other drivers when countDrivers == 1


TODO:
    - compare them to the Laos shifting agriculture  THEY MUST LOOK SIMILAR
    - compare to rubber + cocoa examples THEY MUST LOOK DIFFERENT

'''

In [39]:


label_mapping = {
    'Rural Complex' : 'shifting agriculture',
    'Industrial Forestry' : 'forest plantation',
    'Artisanal Mine' : 'mining',
    'Industrial Mine' : 'mining',
    'Development' : 'urban',
    'Other' : 'other',
    
    
}

,PLOTID,CEO_PLOTID,LON,LAT,ISO,CEO_Ref_Code,Ref_FNF,Ref_LCover,Ref_ChangeType,Ref_ChangeYear,...,Ref_Urb,Ref_ArtAg,Ref_IndAg,Ref_ArtFor,Ref_IndFor,Ref_ArtMine,Ref_IndMine,Ref_Other,DriverGroup,geometry
0,271,9.0,10.684787,6.327598,CMR,142,1,9,Deg,2018.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Rural Complex,POINT (10.68479 6.32760)
1,485,14.0,28.908549,-2.971313,COD,201,1,1,Def,2017.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Rural Complex,POINT (28.90855 -2.97131)
2,1053,38.0,26.425696,-8.005471,COD,116,1,4,Deg,2017.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Rural Complex,POINT (26.42570 -8.00547)
3,1231,41.0,15.738619,6.571221,CAF,248,1,11,Def,2019.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Rural Complex,POINT (15.73862 6.57122)
4,1626,51.0,25.689706,-9.097194,COD,205,1,2,Def,2016.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Rural Complex,POINT (25.68971 -9.09719)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,354749,11690.0,18.381821,1.468611,COD,202,1,1,Def,2018.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Rural Complex,POINT (18.38182 1.46861)
776,354922,11696.0,29.341358,-12.880089,COD,118,1,4,Deg,2019.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Other,POINT (29.34136 -12.88009)
778,356999,NaN,22.631212,4.399095,COD,203,1,1,Def,2019.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Rural Complex,POINT (22.63121 4.39909)
780,358633,11828.0,8.655223,4.499077,CMR,133,1,7,Deg,2019.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Other,POINT (8.65522 4.49908)
781,358637,11829.0,23.676582,8.377913,CAF,119,1,4,Deg,2020.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Other,POINT (23.67658 8.37791)

In [40]:
gdf_filtered = gdf_valid.loc[gdf_valid.countDrivers == 1].reset_index(drop=True)
gdf_filtered = gdf_filtered.loc[gdf_filtered.DriverGroup.isin(label_mapping.keys())]

In [41]:
dataset_prefix = 6000000

In [42]:
gdf_filtered['driver'] = gdf_filtered['DriverGroup'].apply(lambda driver: label_mapping[driver])
gdf_filtered['sampleid'] = range(dataset_prefix, dataset_prefix + len(gdf_filtered))

In [44]:
gdf_final = gdf_filtered[[ 'driver', 'sampleid',
       'geometry']]

In [45]:
gdf_final.to_file('../data/tmp/CAFI.gpkg')

In [46]:
pd.DataFrame(gdf_final).to_csv('../data/labels/CAFI.csv', index=False)