In [7]:
import os

import pandas as pd
import rasterio
import geopandas as gpd
import numpy as np
from shapely.geometry import box

In [3]:
import sys
sys.path.append('../')
from utils import get_tiles_as_gdf, extract_sample, get_window

In [16]:
lc_tiles_dir = '/home/jan/Documents/EPFL/project_2/data/input_datasets/worldcover'
lc_tiles = get_tiles_as_gdf(lc_tiles_dir)

cocoa_ecuador = gpd.read_file('../data/tmp/cacao_ecuador.gpkg')
cocoa_ecuador = cocoa_ecuador.to_crs(4326)

In [18]:
dataset_extent = box(*cocoa_ecuador.total_bounds)

In [20]:
lc_tiles_filtered = lc_tiles.loc[lc_tiles.intersects(dataset_extent)]

In [15]:
#TODO: filter only those cocoa areas that are classified as forest cover by wc
#maybe i need to rasterize the cocoa polygons? might be the easiest way to do it 

for idx, row in lc_tiles_filtered.iterrows():
    cocoa_ecuador

Empty GeoDataFrame
Columns: [geometry, filename]
Index: []

In [21]:
lc_tiles_filtered

,geometry,filename
432,"POLYGON ((-75.00000 0.00000, -75.00000 3.00000...",/home/jan/Documents/EPFL/project_2/data/input_...
433,"POLYGON ((-78.00000 0.00000, -78.00000 3.00000...",/home/jan/Documents/EPFL/project_2/data/input_...
618,"POLYGON ((-75.00000 -3.00000, -75.00000 0.0000...",/home/jan/Documents/EPFL/project_2/data/input_...
619,"POLYGON ((-78.00000 -3.00000, -78.00000 0.0000...",/home/jan/Documents/EPFL/project_2/data/input_...
638,"POLYGON ((-75.00000 -6.00000, -75.00000 -3.000...",/home/jan/Documents/EPFL/project_2/data/input_...
639,"POLYGON ((-78.00000 -6.00000, -78.00000 -3.000...",/home/jan/Documents/EPFL/project_2/data/input_...