In [1]:
import fiona 
import geopandas as gpd
import os 
import pandas as pd
import numpy as np

In [4]:
gdb_file = '/home/jan/Documents/EPFL/project_2/data/input_datasets/sdpt_v2_v11282023.gdb/sdpt_v2_v11282023.gdb'
# Get all the layers from the .gdb file 
layers = fiona.listlayers(gdb_file)

i = 0
gdfs = {}

In [ ]:
skip = True

while i < len(layers):
    
    layer = layers[i]
    i += 1
    if layer == 'chl_plant_v2':
        skip = False
    
    if skip:
        continue
    
    print(layer)
    
    gdf = gpd.read_file(gdb_file,layer=layer)
    print(gdf['originalName'].unique())
    gdfs[layer] = gdf

In [8]:
indo = gdfs['idn_plant_v2']

In [21]:
#indo.loc['caca' in indo['originalName'].str.lower()]

filtered_indo = indo[indo['originalName'].str.lower().str.contains('caca', na=False)]

In [19]:
filtered_indo.to_file('../data/tmp/planted_trees_cacao_indo.gpkg')

In [40]:
cocoa_gdfs = []
coffee_gdfs = []


i = 0

In [5]:


while i < len(layers):
    
    layer = layers[i]
    i += 1
    
    gdf = gpd.read_file(gdb_file,layer=layer)
    gdfs[layer] = gdf
    print(layer)
    cocoa = gdf[gdf['originalName'].str.lower().str.contains('caca', na=False)]
    coffee = gdf[gdf['originalName'].str.lower().str.contains('coffe', na=False)]

    if not cocoa.empty:
        cocoa_gdfs.append(cocoa)
    if not coffee.empty:
        coffee_gdfs.append(coffee)

cri_plant_v2
gab_plant_v2
ken_plant_v2
mmr_plant_v2
mwi_plant_v2
npl_plant_v2
khm_plant_v2
lbr_plant_v2
hnd_plant_v2

NameError: name 'coffee_gdfs' is not defined

In [42]:
cocoa = pd.concat(cocoa_gdfs)
coffee = pd.concat(coffee_gdfs)

In [43]:
cocoa

,Shape_Length,Shape_Area,final_id,iso3,iso2,country,originalName,originalCode,finalCode,vernacName,...,removalFactorAGCBGCMgHaYr,removalFactorAGCBGCstdevMgHaYr,removalFactorAGCMgHaYr,removalFactorAGCstdevMgHaYr,removalFactorSource,removalFactorStdevSource,removalFactorNotes,removalFactorSourceRegion,plantedYear,geometry
2,0.080558,4.025023e-04,COD_3,COD,CD,Democratic Republic of the Congo,cacao,3,3,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2013.0,"MULTIPOLYGON (((20.36443 2.56601, 20.36019 2.5..."
3,0.067938,1.193979e-04,COD_3,COD,CD,Democratic Republic of the Congo,cacao,3,3,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2013.0,"MULTIPOLYGON (((20.23156 2.49491, 20.23089 2.4..."
4,0.135310,7.606693e-04,COD_3,COD,CD,Democratic Republic of the Congo,cacao,3,3,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2011.0,"MULTIPOLYGON (((25.24629 0.84499, 25.24454 0.8..."
5,0.076080,1.119317e-04,COD_3,COD,CD,Democratic Republic of the Congo,cacao,3,3,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2011.0,"MULTIPOLYGON (((17.16213 -1.07162, 17.16461 -1..."
343,0.132678,4.564500e-06,COD_11,COD,CD,Democratic Republic of the Congo,Cacao,3,11,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2000.0,"MULTIPOLYGON (((25.24062 0.83953, 25.23931 0.8..."
366,0.064733,8.830681e-07,COD_11,COD,CD,Democratic Republic of the Congo,Cacao,3,11,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2013.0,"MULTIPOLYGON (((20.36447 2.56601, 20.36024 2.5..."

In [3]:
import geopandas as gpd

In [5]:
coffee = gpd.read_file('/home/jan/Documents/EPFL/project_2/data/tmp/sdpt/coffee.gpkg')

In [9]:
coffee_brazil = coffee.loc[coffee.country == 'Brazil']

In [10]:
coffee_brazil

,final_id,Shape_Length,Shape_Area,iso3,iso2,country,originalName,originalCode,finalCode,vernacName,...,removalFactorAGCBGCMgHaYr,removalFactorAGCBGCstdevMgHaYr,removalFactorAGCMgHaYr,removalFactorAGCstdevMgHaYr,removalFactorSource,removalFactorStdevSource,removalFactorNotes,removalFactorSourceRegion,plantedYear,geometry
32283,BRA_19,0.084547,0.000183,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,1982.0,"MULTIPOLYGON (((-46.90600 -18.52605, -46.90646..."
32284,BRA_19,0.029439,0.000044,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,2012.0,"MULTIPOLYGON (((-46.90989 -18.52741, -46.90924..."
32285,BRA_19,0.019215,0.000014,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,1982.0,"MULTIPOLYGON (((-46.55894 -18.55139, -46.55885..."
32286,BRA_19,0.015659,0.000012,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,1998.0,"MULTIPOLYGON (((-46.56107 -18.55661, -46.56227..."
32287,BRA_19,0.008862,0.000005,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,1982.0,"MULTIPOLYGON (((-46.56641 -18.55878, -46.56762..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32899,BRA_19,0.005901,0.000002,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,1999.0,"MULTIPOLYGON (((-46.81490 -19.42846, -46.81497..."
32900,BRA_19,0.009598,0.000006,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,2007.0,"MULTIPOLYGON (((-46.79584 -19.43694, -46.79588..."
32901,BRA_19,0.034529,0.000057,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,2011.0,"MULTIPOLYGON (((-59.24957 -9.44021, -59.24914 ..."
32902,BRA_19,0.020994,0.000019,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,2014.0,"MULTIPOLYGON (((-59.25392 -9.44592, -59.25376 ..."
32903,BRA_19,0.129054,0.000226,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,2005.0,"MULTIPOLYGON (((-56.34605 -10.12426, -56.34775..."