Here I will fetch data logged to wandb so produce some plots and generally analyse the results

In [43]:
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure


import pandas as pd
import numpy as np
import wandb
api = wandb.Api(timeout=20)

In [63]:
#wandb_id = 'aagly34c' #cartesian3d
wandb_id = 'y0yvlyz1' #4 images


runs = api.runs(path="janpisl/project_2", filters={'name': {'$in': [wandb_id]}})

print(f"matching runs: {len(runs)}")

matching runs: 1

In [64]:
#For each run, request all data and write to a dict
runs_data = []

for run in iter(runs):
    run_dict = {}
    run_dict['logs'] = run.history()
    run_dict['summary'] = run.summary
    run_dict['config'] = run.config

    runs_data.append(run_dict)

In [65]:
#idx = runs_data[0]['logs']['val-loss'].idxmin()
idx = runs_data[0]['logs']['val accuracy'].idxmax()

In [67]:
series = runs_data[0]['logs'].iloc[idx]

In [68]:
img_model_stats = series[[key for key in series.keys() if "val" in key]]

In [70]:
loc_model_stats

soy val f1-score                                                              0.829268
mining val f1-score                                                           0.677327
val conf matrix                      {'path': 'media/images/val conf matrix_38765_5...
pasture val f1-score                                                          0.540452
val-loss                                                                      0.951977
val accuracy                                                                  0.633406
forest regrowth val f1-score                                                  0.394749
palm oil val f1-score                                                         0.590164
coffee val f1-score                                                           0.087912
forest plantation val f1-score                                                0.382503
cocoa val f1-score                                                            0.997743
val macro f1-score                                                            0.595627
shifting agriculture val f1-score                                             0.840027
rubber val f1-score                                                           0.817601
urban val f1-score                                                            0.394149
Name: 492, dtype: object

In [62]:
loc_model_stats = ser[[key for key in ser.keys() if "val" in key]]

In [71]:
kde_stats = {'pasture': 0.4237165582067969,
 'forest plantation': 0.045207956600361664,
 'soy': 0.8578728840625999,
 'coffee': 0.07246376811594205,
 'palm oil': 0.6448893572181243,
 'mining': 0.18608621425522834,
 'urban': 0.5453047775947282,
 'cocoa': 0.9988700564971752,
 'rubber': 0.7730147575544625,
 'forest regrowth': 0.29644533869885986,
 'shifting agriculture': 0.8275862068965517,
 'accuracy': 0.5658204438466712,
 'macro avg': 0.5155870796091664,
 'weighted avg': 0.5172570906810985}

In [72]:
pd.Series(kde_stats)

pasture                 0.423717
forest plantation       0.045208
soy                     0.857873
coffee                  0.072464
palm oil                0.644889
mining                  0.186086
urban                   0.545305
cocoa                   0.998870
rubber                  0.773015
forest regrowth         0.296445
shifting agriculture    0.827586
accuracy                0.565820
macro avg               0.515587
weighted avg            0.517257
dtype: float64

In [92]:
loc_model_stats_edited = {
    key.replace(" val f1-score", ""): value
        for key, value in loc_model_stats.to_dict().items() if "conf" not in key
}

img_model_stats_edited = {
    key.replace(" val f1-score", ""): value
        for key, value in img_model_stats.to_dict().items() if "conf" not in key
}




loc_model_stats_edited = {
    key.replace("val ", ""): value
        for key, value in loc_model_stats_edited.items() 
}

img_model_stats_edited = {
    key.replace("val ", ""): value
        for key, value in img_model_stats_edited.items() 
}

In [97]:
comparison = pd.DataFrame.from_dict(
    [loc_model_stats_edited, img_model_stats_edited, kde_stats])


comparison['model'] =['Location-based nn', 'Image-based nn', 'KDE' ]

In [99]:
comparison = comparison.set_index('model')

In [102]:
comparison

,soy,mining,pasture,val-loss,accuracy,forest regrowth,palm oil,coffee,forest plantation,cocoa,macro f1-score,shifting agriculture,rubber,urban,macro avg,weighted avg
model,,,,,,,,,,,,,,,,
Location-based nn,0.829268,0.677327,0.540452,0.951977,0.633406,0.394749,0.590164,0.087912,0.382503,0.997743,0.595627,0.840027,0.817601,0.394149,NaN,NaN
Image-based nn,0.907486,0.888714,0.769159,0.916092,0.726042,0.586488,0.663284,0.179104,0.618421,0.372019,0.640360,0.721208,0.468048,0.870031,NaN,NaN
KDE,0.857873,0.186086,0.423717,NaN,0.565820,0.296445,0.644889,0.072464,0.045208,0.998870,NaN,0.827586,0.773015,0.545305,0.515587,0.517257

In [104]:
comparison[['accuracy','soy', 'mining', 'pasture','forest regrowth',
       'palm oil', 'coffee', 'forest plantation', 'cocoa', 
       'shifting agriculture', 'rubber', 'urban', ]]

,accuracy,soy,mining,pasture,forest regrowth,palm oil,coffee,forest plantation,cocoa,shifting agriculture,rubber,urban
model,,,,,,,,,,,,
Location-based nn,0.633406,0.829268,0.677327,0.540452,0.394749,0.590164,0.087912,0.382503,0.997743,0.840027,0.817601,0.394149
Image-based nn,0.726042,0.907486,0.888714,0.769159,0.586488,0.663284,0.179104,0.618421,0.372019,0.721208,0.468048,0.870031
KDE,0.565820,0.857873,0.186086,0.423717,0.296445,0.644889,0.072464,0.045208,0.998870,0.827586,0.773015,0.545305