In [5]:
import fiona 
import geopandas as gpd
import os 
import pandas as pd
import numpy as np

In [6]:
gdb_file = '/home/jan/Documents/EPFL/project_2/data/input_datasets/sdpt_v2_v11282023.gdb/sdpt_v2_v11282023.gdb'
# Get all the layers from the .gdb file 
layers = fiona.listlayers(gdb_file)

i = 0
gdfs = {}

In [7]:
print(layers)

['cri_plant_v2', 'gab_plant_v2', 'ken_plant_v2', 'mmr_plant_v2', 'mwi_plant_v2', 'npl_plant_v2', 'khm_plant_v2', 'lbr_plant_v2', 'hnd_plant_v2', 'per_plant_v2', 'phl_plant_v2', 'png_plant_v2', 'rwa_plant_v2', 'nzl_plant_v2', 'tto_plant_v2', 'bgd_plant_v2', 'brn_plant_v2', 'lka_plant_v2', 'nic_plant_v2', 'slb_plant_v2', 'ven_plant_v2', 'gha_plant_v2', 'civ_plant_v2', 'arg_plant_v2', 'cod_plant_v2', 'pan_plant_v2', 'aus_plant_v2', 'bra_plant_v2', 'mex_plant_v2', 'bdi_plant_v2', 'cpv_plant_v2', 'cog_plant_v2', 'slv_plant_v2', 'gnq_plant_v2', 'gin_plant_v2', 'gnb_plant_v2', 'dom_plant_v2', 'stp_plant_v2', 'gmb_plant_v2', 'sen_plant_v2', 'sle_plant_v2', 'tza_plant_v2', 'tgo_plant_v2', 'uga_plant_v2', 'vut_plant_v2', 'blz_plant_v2', 'ecu_plant_v2', 'chl_plant_v2', 'cub_plant_v2', 'col_plant_v2', 'eu_plant_v2', 'aze_plant_v2', 'bol_plant_v2', 'btn_plant_v2', 'cyp_plant_v2', 'fji_plant_v2', 'glp_plant_v2', 'guf_plant_v2', 'hti_plant_v2', 'isr_plant_v2', 'jam_plant_v2', 'jor_plant_v2', 'kgz_plant_v2', 'lbn_plant_v2', 'lso_plant_v2', 'mdg_plant_v2', 'mng_plant_v2', 'moz_plant_v2', 'ncl_plant_v2', 'pry_plant_v2', 'som_plant_v2', 'sur_plant_v2', 'swz_plant_v2', 'syr_plant_v2', 'tun_plant_v2', 'can_plant_v2', 'ind_plant_v2', 'jpn_plant_v2', 'mys_plant_v2', 'usa_plant_v2', 'vnm_plant_v2', 'idn_plant_v2', 'gtm_plant_v2', 'kor_plant_v2', 'ury_plant_v2', 'zaf_plant_v2', 'rus_plant_v2', 'ago_plant_v2', 'arm_plant_v2', 'ben_plant_v2', 'bfa_plant_v2', 'cmr_plant_v2', 'caf_plant_v2', 'egy_plant_v2', 'eri_plant_v2', 'eth_plant_v2', 'irn_plant_v2', 'irq_plant_v2', 'kaz_plant_v2', 'lby_plant_v2', 'mli_plant_v2', 'mar_plant_v2', 'mrt_plant_v2', 'nga_plant_v2', 'omn_plant_v2', 'pak_plant_v2', 'ssd_plant_v2', 'tjk_plant_v2', 'tur_plant_v2', 'uzb_plant_v2', 'zmb_plant_v2', 'zwe_plant_v2', 'dza_plant_v2', 'tha_plant_v2', 'lao_plant_v2', 'chn_plant_v2', 'prk_plant_v2']

In [8]:
skip = True

while i < len(layers):
    
    layer = layers[i]
    i += 1
    if layer == 'bra_plant_v2':
        skip = False
    
    if skip:
        continue
    
    print(layer)
    
    gdf = gpd.read_file(gdb_file,layer=layer)
    print(gdf['originalName'].unique())
    gdfs[layer] = gdf

bra_plant_v2
['Large industrial plantation, Eucalyptus, transparent world'
 'Clearing,  very young plantation, n, a, transparent world'
 'Mosaic of medium-sized plantations, Eucalyptus, transparent world'
 'Large industrial plantation, Pine, transparent world'
 'Large industrial plantation, gr-Fruit, transparent world'
 'Large industrial plantation, Hevea, transparent world'
 'Large industrial plantation, gr-Palms,  gr-Fruit, transparent world'
 'Large industrial plantation, Banana, transparent world'
 'Large industrial plantation, Araucaria, transparent world'
 'Large industrial plantation, Unknown, transparent world'
 'Large industrial plantation, Coconut palm, transparent world'
 'Large industrial plantation, gr-Citrus, transparent world'
 'Large industrial plantation, Acacia, transparent world'
 'Mosaic of medium-sized plantations, Banana, transparent world'
 'Large industrial plantation, Coffee, transparent world'
 'Large industrial plantation, Oil palm, transparent world'
 'Mosaic of medium-sized plantations, Hevea, transparent world'
 'Mosaic of medium-sized plantations, Coconut palm, transparent world'
 'Large industrial plantation, Cashew, transparent world'
 'Mosaic of medium-sized plantations, Cashew, transparent world'
 'Mosaic of small-sized plantations, Cashew, transparent world'
 'Large industrial plantation, Bamboo, transparent world'
 'Mosaic of medium-sized plantations, gr-Palms,  gr-Fruit, transparent world'
 'Mosaic of medium-sized plantations, gr-Fruit, transparent world'
 'Mosaic of small-sized plantations, gr-Palms,  gr-Fruit, transparent world'
 'Mosaic of medium-sized plantations, Unknown, transparent world'
 'Mosaic of small-sized plantations, Mixed trees,, transparent world'
 'Orchard' 'Oil Palm']
mex_plant_v2
['SWIETENIA MACROPHYLLA, TABEBUIA ROSEA' 'TABEBUIA DONNELL-SMITHII'
 'PINUS GREGGII' 'PINUS ENGELMANNII' 'GMELINA ARBOREA'
 'SWIETENIA MACROPHYLLA' 'CORDIA DODECANDRA, PLATYMISCIUM YUCATANUM'
 'HAEMATOXYLUM CAMPECHIANUM' 'GMELINA ARBOREA, SWIETENIA MACROPHYLLA'
 'TABEBUIA ROSEA' 'HEVEA BRASILIENSIS' 'CEDRELA ODORATA' 'PINUS COOPERI'
 'PINUS AYACAHUITE, PSEUDOTSUGA MENZIESII'
 'PINUS GREGGII, PINUS MONTEZUMAE' 'PINUS OOCARPA' 'LEUCAENA LEUCOCEPHALA'
 'CAESALPINIA PLATYLOBA' 'CAESALPINIA PLATYLOBA, TABEBUIA ROSEA'
 'PINUS MONTEZUMAE' 'PINUS PATULA' 'BAMBUSA OLDHAMII'
 'PINUS PATULA, PINUS PSEUDOSTROBUS' 'PINUS PSEUDOSTROBUS'
 'PINUS MONTEZUMAE, PINUS PATULA' 'PINUS GREGGII, PINUS PSEUDOSTROBUS'
 'EUCALYPTUS PELLITA, TABEBUIA ROSEA' 'TECTONA GRANDIS' 'ACACIA MANGIUM'
 'EUCALYPTUS CAMALDULENSIS' 'PROSOPIS GLANDULOSA' 'PROSOPIS LAEVIGATA'
 'PINUS CARIBAEA'
 'GMELINA ARBOREA, SWIETENIA MACROPHYLLA, TECTONA GRANDIS'
 'PINUS AYACAHUITE' 'PINUS PATULA, PINUS GREGGII'
 'PINUS GREGGII, PINUS PATULA' 'EUCALYPTUS UROPHYLLA'
 'PINUS CARIBAEA, PINUS ELLIOTTII'
 'PINUS AYACAHUITE, ABIES RELIGIOSA, PSEUDOTSUGA MENZIESII'
 'PINUS MONTEZUMAE, PINUS HARTWEGII' 'PINUS GREGGII, PINUS CEMBROIDES'
 'CHAMAEDOREA POCHUTLENSIS' 'SWIETENIA MACROPHYLLA, TECTONA GRANDIS'
 'TECTONA GRANDIS, GMELINA ARBOREA'
 'CEDRELA ODORATA, SWIETENIA MACROPHYLLA, TABEBUIA DONNELL-SMITHII, TABEBUIA ROSEA, CORDIA BICOLOR, CORDIA ALLIADORA, ENTEROLOBIUM CYCLOCARPUM, TECTONA GRANDIS, GMELINA ARBOREA.'
 'PINUS PSEUDOSTROBUS, PINUS MONTEZUMAE, PINUS PATULA'
 'PINUS PSEUDOSTROBUS, PINUS PATULA' 'KHAYA SENEGALENSIS, TABEBUIA ROSEA'
 'EUCALYPTUS CAMALDULENSIS, EUCALIPTUS UROPHYLLA' 'MELIA AZEDARACH'
 'TECTONA GRANDIS, TABEBUIA ROSEA, TABEBUIA DONNELL-SMITHII'
 'PINUS MONTEZUMAE, PINUS PSEUDOSTROBUS'
 'PINUS GREGGII, PINUS PATULA, PINUS MONTEZUMAE, QUERCUS SPP.'
 'PINUS LEIOPHYLLA' 'PINUS DOUGLASIANA, PINUS DEVONIANA'
 'PINUS PATULA, PINUS AYACAHUITE' 'ENTEROLOBIUM CYCLOCARPUM'
 'TECTONA GRANDIS, TABEBUIA ROSEA' 'EUCALYPTUS SP.'
 'KHAYA SENEGALENSIS, SWIETENIA MACROPHYLLA, TECTONA GRANDIS'
 'PINUS CHIAPENSIS' 'PSEUDOTSUGA MENZIESII'
 'PINUS AYACAHUITE, ABIES RELIGIOSA'
 'GUADUA ANGUSTIFOLIA, BAMBUSA OLDHAMII'
 'TECTONA GRANDIS, SWIETENIA MACROPHYLLA, CEDRELA ODORATA'
 'EUCALYPTUS PELLITA, ACACIA MANGIUM'
 'TABEBUIA ROSEA, CORDIA DODECANDRA, SWIETENIA MACROPHYLLA'
 'GUADUA ANGUSTIFOLIA' 'TABEBUIA ROSEA, TECTONA GRANDIS'
 'BAMBUSA VULGARIS, BAMBUSA OLDHAMII, GUADUA ANGUSTIFOLIA'
 'BAMBUSA VULGARIS, GUADUA ANGUSTIFOLIA' 'ABIES RELIGIOSA'
 'PINUS PATULA, PINUS GREGGII, PINUS PSEUDOSTROBUS, PINUS MONTEZUMAE'
 'PINUS AYACAHUITE, PINUS PSEUDOSTROBUS'
 'GMELINA ARBOREA, SWIETENIA HUMILIS'
 'ABIES RELIGIOSA, PINUS MONTEZUMAE, PINUS PATULA'
 'PINUS PATULA, PINUS GREGGII, PINUS AYACAHUITE, PINUS MONTEZUMAE'
 'ACACIA GUATEMALENSIS, GMELINA ARBOREA'
 'PINUS LEIOPHYLLA, PINUS PSEUDOSTROBUS' 'PINUS DOUGLASIANA'
 'PINUS DEVONIANA' 'LEUCAENA LEUCOCEPHALA, CAESALPINIA PLATYLOBA'
 'PINUS PSEUDOSTROBUS, PINUS DEVONIANA'
 'PINUS PSEUDOSTROBUS, PINUS GREGGII' 'CHAMAEDOREA ELEGANS'
 'PINUS PSEUDOSTROBUS, PINUS MONTEZUMAE' 'PINUS CEMBROIDES'
 'PINUS PATULA, PINUS GREGGII, PINUS MONTEZUMAE'
 'PINUS PATULA, PINUS PSEUDOSTROBUS, PINUS MONTEZUMAE'
 'KHAYA SENEGALENSIS, TABEBUIA ROSEA, SWIETENIA MACROPHYLLA, TECTONA GRANDIS'
 'EUCALYPTUS UROPHYLLA, TECTONA GRANDIS' 'EUCALYPTUS UROGRANDIS'
 'EUCALYPTUS GRANDIS' 'CHAMAEDOREA RADICALIS'
 'EUCALYPTUS CAMALDULENSIS, TECTONA GRANDIS' 'PSEUDOTSUGA SP.'
 'PINUS CHIAPENSIS, PINUS PATULA'
 'TECTONA GRANDIS, GMELINA ARBOREA, TABEBUIA DONNELL-SMITHII, TABEBUIA ROSEA'
 'TABEBUIA ROSEA, TABEBUIA DONNELL-SMITHII'
 'ABIES RELIGIOSA, PSEUDOTSUGA MENZIESII'
 'GMELINA ARBOREA, TECTONA GRANDIS, SWIETENIA HUMILIS'
 'ABIES RELIGIOSA, PINUS AYACAHUITE'
 'PSEUDOTSUGA MENZIESII, ABIES RELIGIOSA, PINUS PSEUDOSTROBUS, PINUS MONTEZUMAE, PINUS PATULA'
 'PINUS LEIOPHYLLA, PINUS ELLIOTTII, PINUS PRINGLEI'
 'PINUS DEVONIANA, PINUS GREGGII' 'PINUS PATULA, PINUS DEVONIANA'
 'PINUS PRINGLEI, PINUS LAWSONII' 'TABEBUIA ROSEA, SWIETENIA MACROPHYLLA'
 'PINUS PSEUDOSTROBUS, PINUS PATULA, PINUS AYACAHUITE'
 'PINUS PATULA, PINUS MONTEZUMAE'
 'PINUS GREGGII, PINUS PSEUDOSTROBUS, PINUS MONTEZUMAE'
 'GMELINA ARBOREA, OCOTEA PUBERULA'
 'CHAMAECYPARIS THYOIDES, CHAMAECYPARIS LAWSONIANA'
 'PINUS MONTEZUMAE, PINUS PATULA, PINUS PSEUDOSTROBUS' 'OCOTEA PUBERULA'
 'KHAYA SENEGALENSIS, SWIETENIA MACROPHYLLA, TABEBUIA ROSEA, TECTONA GRANDIS'
 'EUCALYPTUS UROGRANDIS, EUCALYPTUS GRANDIS' 'EUCALYPTUS PELLITA'
 'ACACIA MANGIUM, EUCALYPTUS PELLITA'
 'GMELINA ARBOREA, EUCALYPTUS UROGRANDIS'
 'GMELINA ARBOREA, TECTONA GRANDIS, SWIETENIA MACROPHYLLA, TABEBUIA DONNELL-SMITHII'
 'CORDIA ALLIADORA, TABEBUIA DONNELL-SMITHII' 'CORDIA ALLIADORA'
 'CEDRELA ODORATA, SWIETENIA MACROPHYLLA, TABEBUIA ROSEA, TABEBUIA DONNELL-SMITHII'
 'GMELINA ARBOREA, TECTONA GRANDIS, TABEBUIA ROSEA' 'CORDIA DODECANDRA'
 'CEDRELA ODORATA, TABEBUIA DONNELL-SMITHII'
 'TABEBUIA DONNELL-SMITHII, CEDRELA ODORATA'
 'TECTONA GRANDIS, SWIETENIA MACROPHYLLA, TABEBUIA ROSEA'
 'PINUS COOPERI, PINUS DURANGENSIS, PINUS ENGELMANNII'
 'PINUS ENGELMANNII, PINUS COOPERI' 'PINUS COOPERI, PINUS ENGELMANNII'
 'PINUS ELDARICA'
 'SWIETENIA HUMILIS, TABEBUIA ROSEA, GMELINA ARBOREA, TECTONA GRANDIS'
 'TABEBUIA ROSEA, GMELINA ARBOREA, TECTONA GRANDIS'
 'SWIETENIA HUMILIS, TABEBUIA ROSEA'
 'PINUS PATULA, PINUS PSEUDOSTROBUS, PINUS MONTEZUMAE, PINUS LEIOPHYLLA'
 'PINUS AYACAHUITE, PSEUDOTSUGA MENZIESII, CUPRESSUS LINDLEYI'
 'ABIES RELIGIOSA, PSEUDOTSUGA MENZIESII, PINUS AYACAHUITE'
 'PINUS AYACAHUITE, PSEUDOTSUGA MENZIESII, ABIES RELIGIOSA'
 'PINUS AYACAHUITE, PINUS HARTWEGII'
 'PINUS GREGGII, PINUS PATULA, PINUS PSEUDOSTROBUS'
 'PINUS GREGGII, PINUS MONTEZUMAE, PINUS PSEUDOSTROBUS'
 'PINUS DEVONIANA, PINUS PSEUDOSTROBUS'
 'PINUS OOCARPA, PINUS PRINGLEI Y PINUS ELLIOTTII'
 'PINUS LEIOPHYLLA, PINUS LAWSONII' 'PINUS DOUGLASIANA, PINUS OOCARPA'
 'ACACIA FARNESIANA, LEUCAENA LEUCOCEPHALA'
 'PINUS GREGGII, PINUS OAXACANA'
 'PINUS PATULA, PINUS PSEUDOSTROBUS, PINUS AYACAHUITE'
 'PINUS CEMBROIDES, PINUS PSEUDOSTROBUS'
 'SWIETENIA MACROPHYLLA, GMELINA ARBOREA'
 'PINUS PSEUDOSTROBUS, PINUS TEOCOTE' 'PINUS MONTEZUMAE, PINUS GREGGII'
 'SWIETENIA MACROPHYLLA, CEDRELA ODORATA, TABEBUIA ROSEA'
 'KHAYA SENEGALENSIS'
 'TABEBUIA ROSEA, SWIETENIA MACROPHYLLA, KHAYA SENEGALENSIS, TECTONA GRANDIS'
 'HEVEA BRASILIENSIS, SWIETENIA MACROPHYLLA'
 'TECTONA GRANDIS, EUCALYPTUS GRANDIS' 'GMELINA ARBOREA, TECTONA GRANDIS'
 'TECTONA GRANDIS, CORDIA ALLIADORA, GMELINA ARBOREA'
 'PINUS CEMBROIDES, PINUS GREGGII' 'YUCCA SCHIDIGERA'
 'TECTONA GRANDIS, CEDRELA ODORATA' 'JATROPHA CURCAS'
 'TABEBUIA DONNELL-SMITHII, TECTONA GRANDIS'
 'TABEBUIA DONNELL-SMITHII, TABEBUIA ROSEA, TECTONA GRANDIS'
 'ACROCARPUS FRAXINIFOLIUS, GMELINA ARBOREA'
 'TABEBUIA DONNELL-SMITHII, TECTONA GRANDIS Y TABEBUIA ROSEA'
 'TABEBUIA DONNELL-SMITHII, TABEBUIA ROSEA'
 'TABEBUIA ROSEA, TABEBUIA DONNELL-SMITHII, TECTONA GRANDIS, SWIETENIA MACROPHYLLA'
 'SWIETENIA MACROPHYLLA, TABEBUIA DONNELL-SMITHII'
 'PINUS GREGGII, PINUS ELDARICA' 'PINUS AYACAHUITE, PSEUDOTSUGA TAXIFOLIA'
 'PINUS PATULA, PINUS GREGGII, PINUS PSEUDOSTROBUS, CUPRESSUS LINDLEYI'
 'TABEBUIA ROSEA, SWIETENIA HUMILIS, ACACIA GUATEMALENSIS, SWIETENIA MACROPHYLLA, ENTEROLOBIUM CYCLOCARPUM'
 'PINUS PATULA, PINUS GREGGII, FRAXINUS UHDEI'
 'PINUS AYACAHUITE, PINUS PATULA'
 'PINUS PATULA, PINUS MONTEZUMAE, PINUS PSEUDOSTROBUS, PINUS GREGGII'
 'EUCALYPTUS SP., TABEBUIA ROSEA, GMELINA ARBOREA' 'PINUS HARTWEGII'
 'PINUS HARTWEGII, PINUS MONTEZUMAE'
 'PINUS AYACAHUITE, PINUS PATULA, PINUS PSEUDOSTROBUS'
 'PINUS PATULA, PINUS GREGGII, PINUS PSEUDOSTROBUS'
 'PSEUDOTSUGA MENZIESII, ABIES RELIGIOSA, PINUS AYACAHUITE'
 'PINUS AYACAHUITE, PSEUDOTSUGA MENZIESII, ABIES RELIGIOSA, PINUS MONTEZUMAE'
 'PINUS AYACAHUITE, PINUS MONTEZUMAE'
 'TABEBUIA ROSEA, CAESALPINIA PLATYLOBA'
 'CEDRELA ODORATA, SWIETENIA MACROPHYLLA, TABEBUIA ROSEA'
 'TECTONA GRANDIS, SWIETENIA MACROPHYLLA, GMELINA ARBOREA'
 'SWIETENIA MACROPHYLLA, CORDIA ALLIADORA Y TABEBUIA ROSEA'
 'SWIETENIA MACROPHYLLA, CEDRELA ODORATA'
 'CEDRELA ODORATA, SWIETENIA MACROPHYLLA'
 'PINUS MONTEZUMAE, PINUS GREGGII, PINUS PSEUDOSTROBUS'
 'PINUS PATULA, PINUS MONTEZUMAE, PINUS GREGGII' 'PINUS TEOCOTE'
 'PINUS PATULA, PINUS TEOCOTE' 'EUCALYPTUS GLOBULUS'
 'GMELINA ARBOREA, EUCALYPTUS SP.'
 'SWIETENIA MACROPHYLLA, CEDRELA ODORATA, GMELINA  ARBOREA, TECTONA GRANDIS'
 'PROSOPIS JULIFLORA' 'PROSOPIS GLANDULOSA, PROSOPIS LAEVIGATA'
 'EUCALYPTUS PELLITA, TECTONA GRANDIS' 'PINUS TEOCOTE, CUPRESSUS SP.'
 'PINUS GREGGII, CUPRESSUS SP.' 'PINUS PSEUDOSTROBUS, PINUS AYACAHUITE'
 'CUPRESSUS SP., PINUS PSEUDOSTROBUS'
 'PINUS PATULA, CUPRESSUS LINDLEYI, PINUS MONTEZUMAE'
 'GMELINA ARBOREA, EUCALYPTUS UROPHYLLA' 'CEIBA PENTANDRA'
 'YUCCA FILIFERA'
 'GMELINA ARBOREA, TABEBUIA ROSEA, TABEBUIA DONNELL-SMITHII'
 'TABEBUIA ROSEA, SWIETENIA HUMILIS'
 'SWIETENIA MACROPHYLLA, TECTONA GRANDIS, TABEBUIA ROSEA,TABEBUIA DONNELL-SMITHII'
 'EUCALYPTUS NITENS'
 'ABIES RELIGIOSA, PSEUDOTSUGA SPP., CUPRESSUS LINDLEYI, PINUS AYACAHUITE'
 'CEDRELA ODORATA, SWIETENIA MACROPHYLLA, QUERCUS MAGNOLIIFOLIA, ENTEROLOBIUM CYCLOCARPUM'
 'SWIETENIA MACROPHYLLA, TABEBUIA PALMERI'
 'GMELINA ARBOREA, SWIETENIA HUMILIS, ENTEROLOBIUM CYCLOCARPUM, EUCALYPTUS CAMALDULENSIS, QUERCUS MAGNOLIIFOLIA'
 'CEDRELA ODORATA, TABEBUIA ROSEA'
 'ENTEROLOBIUM CYCLOCARPUM, TABEBUIA ROSEA'
 'PINUS OOCARPA, PINUS CARIBAEA'
 'SWIETENIA MACROPHYLLA, TABEBUIA DONNELL-SMITHII, CEDRELA ODORATA'
 'PINUS PATULA, PINUS AYACAHUITE, PINUS MONTEZUMAE'
 'BAMBUSA OLDHAMII, GUADUA ANGUSTIFOLIA'
 'PINUS CHIAPENSIS, PINUS GREGGII, PINUS AYACAHUITE'
 'PINUS PATULA, PINUS PSEUDOSTROBUS, PINUS GREGGII'
 'PINUS PATULA, PINUS MONTEZUMAE, PINUS PSEUDOSTROBUS'
 'ENTEROLOBIUM CYCLOCARPUM, SWIETENIA MACROPHYLLA'
 'CEDRELA ODORATA, TABEBUIA ROSEA, SWIETENIA MACROPHYLLA, GMELINA ARBOREA'
 'TECTONA GRANDIS, TABEBUIA ROSEA, CEDRELA ODORATA'
 'GMELINA ARBOREA, EUCALYPTUS CAMALDULENSIS'
 'PINUS AYACAHUITE, PINUS MONTEZUMAE, PINUS GREGGII, PINUS CEMBROIDES'
 'TECTONA GRANDIS, SWIETENIA MACROPHYLLA, CEDRELA ODORATA, TABEBUIA ROSEA'
 'PINUS PATULA, PINUS MONTEZUMAE, PINUS PSEUDOSTROBUS, PINUS TEOCOTE'
 'GMELINA ARBOREA, TABEBUIA ROSEA'
 'TABEBUIA ROSEA, SWIETENIA HUMILIS, CORDIA ELAEAGNOIDES'
 'CEDRELA ODORATA, TABEBUIA DONNELL-SMITHII, SWIETENIA MACROPHYLLA'
 'CEDRELA ODORATA, ACROCARPUS FRAXINIFOLIUS'
 'TABEBUIA ROSEA, CEDRELA ODORATA, TABEBUIA DONNELL-SMITHII'
 'TABEBUIA ROSEA, ENTEROLOBIUM CYCLOCARPUM'
 'TABEBUIA ROSEA, TABEBUIA DONNELL-SMITHII, SWIETENIA HUMILIS'
 'TABEBUIA ROSEA, TABEBUIA DONNELL-SMITHII, HURA POLYANDRA, ENTEROLOBIUM CYCLOCARPUM'
 'PINUS PRINGLEI, PINUS LEIOPHYLLA' 'PINUS LEIOPHYLLA, PINUS PRINGLEI'
 'TABEBUIA ROSEA, SWIETENIA MACROPHYLLA, EBENOPSIS EBANO, MELIA AZEDARACH, PINUS GREGGII'
 'PROSOPIS VELUTINA' 'TECTONA GRANDIS, EUCALYPTUS UROPHYLLA'
 'TECTONA GRANDIS, TABEBUIA ROSEA, GMELINA ARBOREA, SWIETENIA MACROPHYLLA'
 'EUCALYPTUS CAMALDULENSIS, GMELINA ARBOREA, TABEBUIA ROSEA'
 'TABEBUIA DONNELL-SMITHII, TABEBUIA ROSEA, GMELINA ARBOREA, TECTONA GRANDIS'
 'TABEBUIA DONNELL-SMITHII, TABEBUIA ROSEA, GMELINA ARBOREA'
 'ACROCARPUS FRAXINIFOLIUS'
 'SWIETENIA MACROPHYLLA, TECTONA GRANDIS, TABEBUIA ROSEA'
 'SWIETENIA HUMILIS'
 'ENTEROLOBIUM CYCLOCARPUM, SWIETENIA HUMILIS, TABEBUIA ROSEA'
 'TABEBUIA ROSEA, ENTEROLOBIUM CYCLOCARPUM, CEDRELA ODORATA'
 'TABEBUIA ROSEA, SWIETENIA HUMILIS, ENTEROLOBIUM CYCLOCARPUM'
 'CEDRELA ODORATA, ENTEROLOBIUM CYCLOCARPUM, SWIETENIA HUMILIS, TABEBUIA ROSEA'
 'SABAL MEXICANA' 'PINUS PATULA, PINUS MONTEZUMAE, CUPRESSUS LINDLEYI'
 'PINUS OOCARPA, PINUS LAWSONII'
 'PINUS  ELLIOTTII, PINUS OOCARPA, PINUS CARIBAEA, PINUS PRINGLEI, PINUS LAWSONII'
 'PINUS PSEUDOSTROBUS, PINUS AYACAHUITE, PINUS PATULA' 'MORINGA OLEIFERA'
 'CEDRELA ODORATA, GMELINA ARBOREA, SWIETENIA MACROPHYLLA'
 'CEDRELA ODORATA, TECTONA GRANDIS, GMELINA ARBOREA, TABEBUIA ROSEA, SWIETENIA'
 'CEDRELA ODORATA, TABEBUIA ROSEA, TECTONA GRANDIS'
 'HAEMATOXYLUM CAMPECHIANUM, GMELINA ARBOREA' 'BLEPHARIDIUM MEXICANUM'
 'GMELINA ARBOREA, EUCALYPTUS GRANDIS'
 'EUCALYPTUS UROPHYLLA, HEVEA BRASILIENSIS, SWIETENIA MACROPHYLLA'
 'HEVEA BRASILIENSIS, EUCALYPTUS UROPHYLLA'
 'EUCALYPTUS SP., GMELINA ARBOREA'
 'TECTONA GRANDIS, SWIETENIA MACROPHYLLA'
 'EUCALYPTUS UROPHYLLA, EUCALYPTUS GRANDIS, GMELINA ARBOREA'
 'EUCALYPTUS NITENS, EUCALYPTUS GLOBULUS, GMELINA ARBOREA'
 'HEVEA BRASILIENSIS, TABEBUIA ROSEA'
 'HEVEA BRASILIENSIS, TABEBUIA ROSEA, CEDRELA ODORATA'
 'AZADIRACHTA INDICA'
 'CEDRELA ODORATA, SWIETENIA MACROPHYLLA, TECTONA GRANDIS'
 'CAESALPINIA PLATYLOBA, ACACIA MANGIUM'
 'GMELINA ARBOREA, PROSOPIS LAEVIGATA, TECTONA GRANDIS'
 'PINUS GREGGII, PINUS MONTEZUMAE, PINUS PATULA'
 'PINUS PATULA, PINUS AYACAHUITE, PINUS PSEUDOSTROBUS'
 'PINUS AYACAHUITE, PINUS MONTEZUMAE, PINUS PATULA'
 'PINUS MONTEZUMAE, PINUS PSEUDOSTROBUS, PINUS PATULA'
 'PINUS GREGGII, CAESALPINIA PLATYLOBA, LEUCAENA LEUCOCEPHALA'
 'TABEBUIA DONNELL-SMITHII, SWIETENIA MACROPHYLLA'
 'HAEMATOXYLUM CAMPECHIANUM, TABEBUIA ROSEA'
 'TABEBUIA ROSEA, CORDIA ELAEAGNOIDES, TECTONA GRANDIS, SWIETENIA HUMILIS'
 'CHAMAEDOREA ELEGANS, CHAMAEDOREA TEPEJILOTE'
 'GMELINA ARBOREA, ACACIA MANGIUM'
 'TECTONA GRANDIS, CEDRELA ODORATA, TABEBUIA DONNELL-SMITHII'
 'Induced Forest' 'Induced Palm Grove' 'oil palm' 'orchard']
bdi_plant_v2

['Oil Palm' 'Orchard']
cpv_plant_v2
['Plantation' 'Orchard']
cog_plant_v2
['Oil Palm' 'Orchard']
slv_plant_v2
['Oil Palm' 'Orchard']
gnq_plant_v2
['Oil Palm' 'Orchard']
gin_plant_v2
['Plantation' 'Oil Palm' 'Orchard']
gnb_plant_v2
['Plantation' 'Oil Palm' 'Orchard']
dom_plant_v2
['Oil Palm' 'Orchard']
stp_plant_v2
['Oil Palm' 'Orchard']
gmb_plant_v2
['Plantation' 'Orchard']
sen_plant_v2
['Plantation' 'Orchard']
sle_plant_v2
['Plantation' 'Oil Palm' 'Orchard']
tza_plant_v2
['Oil Palm' 'Orchard']
tgo_plant_v2
['Plantation' 'Oil Palm' 'Orchard']
uga_plant_v2
['Oil Palm' 'Orchard']
vut_plant_v2
['Oil Palm' 'Orchard']
blz_plant_v2
['Citrus' 'Banana' 'Coconut' 'Oil Palm' 'Orchard']
ecu_plant_v2
['Pinus patula' 'Gmelina arborea' 'Tectona grandis' 'Cordia alliodora'
 'Persea americana' 'Pinus radiata' 'Eucalyptus globulus'
 'Ochroma pyramidale' 'Triplaris cumingiana' 'Schizolobium parahybum'
 'Prosopis juliflora' 'Jacaranda copaia' 'Alnus acuminata'
 'Eucalyptus saligna' 'Hevea brasiliensis' 'Eucalyptus urograndis'
 'Cedrelinga catenaeformis' 'Forest Plantations' 'Oil Palm' 'Orchard']
chl_plant_v2

KeyboardInterrupt:

In [18]:
gdfs['bra_plant_v2'].reference.unique()

array(['Petersen et al. (2016)', 'Open street map',
       'Descals et al. (2021)'], dtype=object)

In [12]:
gdf = gdfs['bra_plant_v2']

In [13]:
coffee = gdf[gdf['originalName'].str.lower().str.contains('coffe', na=False)]

In [19]:
coffee.reference.unique()

array(['Petersen et al. (2016)'], dtype=object)

In [16]:
coffee[['sciName11', 'sciName12', 'sciName13', 'simpleType', 'leafStatus',
       'leafType', 'woodType', 'sizeCategory', 'ownership', 'reference',
       'imageryYear', 'method', 'removalFactorAGCBGCMgHaYr']]

,sciName11,sciName12,sciName13,simpleType,leafStatus,leafType,woodType,sizeCategory,ownership,reference,imageryYear,method,removalFactorAGCBGCMgHaYr
175723,None,None,None,Tree crops,NA,NA,NA,Large Industrial,Unknown,Petersen et al. (2016),2013-2014,Manual polygon delineation | Supervised classi...,3.67
175902,None,None,None,Tree crops,NA,NA,NA,Large Industrial,Unknown,Petersen et al. (2016),2013-2014,Manual polygon delineation | Supervised classi...,3.67
176114,None,None,None,Tree crops,NA,NA,NA,Large Industrial,Unknown,Petersen et al. (2016),2013-2014,Manual polygon delineation | Supervised classi...,3.67
176168,None,None,None,Tree crops,NA,NA,NA,Large Industrial,Unknown,Petersen et al. (2016),2013-2014,Manual polygon delineation | Supervised classi...,3.67
176189,None,None,None,Tree crops,NA,NA,NA,Large Industrial,Unknown,Petersen et al. (2016),2013-2014,Manual polygon delineation | Supervised classi...,3.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...
187222,None,None,None,Tree crops,NA,NA,NA,Large Industrial,Unknown,Petersen et al. (2016),2013-2014,Manual polygon delineation | Supervised classi...,3.67
187318,None,None,None,Tree crops,NA,NA,NA,Large Industrial,Unknown,Petersen et al. (2016),2013-2014,Manual polygon delineation | Supervised classi...,3.67
239348,None,None,None,Tree crops,NA,NA,NA,Large Industrial,Unknown,Petersen et al. (2016),2013-2014,Manual polygon delineation | Supervised classi...,3.67
239349,None,None,None,Tree crops,NA,NA,NA,Large Industrial,Unknown,Petersen et al. (2016),2013-2014,Manual polygon delineation | Supervised classi...,3.67
239510,None,None,None,Tree crops,NA,NA,NA,Large Industrial,Unknown,Petersen et al. (2016),2013-2014,Manual polygon delineation | Supervised classi...,3.67

In [8]:
indo = gdfs['idn_plant_v2']

In [21]:
#indo.loc['caca' in indo['originalName'].str.lower()]

filtered_indo = indo[indo['originalName'].str.lower().str.contains('caca', na=False)]

In [19]:
filtered_indo.to_file('../data/tmp/planted_trees_cacao_indo.gpkg')

In [40]:
cocoa_gdfs = []
coffee_gdfs = []


i = 0

In [5]:


while i < len(layers):
    
    layer = layers[i]
    i += 1
    
    gdf = gpd.read_file(gdb_file,layer=layer)
    gdfs[layer] = gdf
    print(layer)
    cocoa = gdf[gdf['originalName'].str.lower().str.contains('caca', na=False)]
    coffee = gdf[gdf['originalName'].str.lower().str.contains('coffe', na=False)]

    if not cocoa.empty:
        cocoa_gdfs.append(cocoa)
    if not coffee.empty:
        coffee_gdfs.append(coffee)

cri_plant_v2
gab_plant_v2
ken_plant_v2
mmr_plant_v2
mwi_plant_v2
npl_plant_v2
khm_plant_v2
lbr_plant_v2
hnd_plant_v2

NameError: name 'coffee_gdfs' is not defined

In [42]:
cocoa = pd.concat(cocoa_gdfs)
coffee = pd.concat(coffee_gdfs)

In [43]:
cocoa

,Shape_Length,Shape_Area,final_id,iso3,iso2,country,originalName,originalCode,finalCode,vernacName,...,removalFactorAGCBGCMgHaYr,removalFactorAGCBGCstdevMgHaYr,removalFactorAGCMgHaYr,removalFactorAGCstdevMgHaYr,removalFactorSource,removalFactorStdevSource,removalFactorNotes,removalFactorSourceRegion,plantedYear,geometry
2,0.080558,4.025023e-04,COD_3,COD,CD,Democratic Republic of the Congo,cacao,3,3,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2013.0,"MULTIPOLYGON (((20.36443 2.56601, 20.36019 2.5..."
3,0.067938,1.193979e-04,COD_3,COD,CD,Democratic Republic of the Congo,cacao,3,3,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2013.0,"MULTIPOLYGON (((20.23156 2.49491, 20.23089 2.4..."
4,0.135310,7.606693e-04,COD_3,COD,CD,Democratic Republic of the Congo,cacao,3,3,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2011.0,"MULTIPOLYGON (((25.24629 0.84499, 25.24454 0.8..."
5,0.076080,1.119317e-04,COD_3,COD,CD,Democratic Republic of the Congo,cacao,3,3,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2011.0,"MULTIPOLYGON (((17.16213 -1.07162, 17.16461 -1..."
343,0.132678,4.564500e-06,COD_11,COD,CD,Democratic Republic of the Congo,Cacao,3,11,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2000.0,"MULTIPOLYGON (((25.24062 0.83953, 25.23931 0.8..."
366,0.064733,8.830681e-07,COD_11,COD,CD,Democratic Republic of the Congo,Cacao,3,11,Cacao,...,3.87,2.3711,3.16,2.37,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,Africa tropical wet shaded perennial default r...,Africa - tropical wet,2013.0,"MULTIPOLYGON (((20.36447 2.56601, 20.36024 2.5..."

In [1]:
import geopandas as gpd

In [2]:
coffee = gpd.read_file('/home/jan/Documents/EPFL/project_2/data/tmp/sdpt/coffee.gpkg')

In [ ]:
coffee

In [16]:
coffee_brazil = coffee.loc[coffee.country == 'Brazil']

In [5]:
#utm = coffee_brazil.estimate_utm_crs()
#coffee_brazil_utm = coffee_brazil.to_crs(utm)

In [7]:
import geopandas as gpd
import rasterio
from rasterio.features import rasterize
from rasterio.transform import from_origin

In [23]:
amazon_coffee = coffee_brazil.loc[coffee_brazil.index.isin([32901,32902,32903])]
rest = coffee_brazil.loc[~coffee_brazil.index.isin([32901,32902,32903])]

In [24]:
amazon_coffee

,final_id,Shape_Length,Shape_Area,iso3,iso2,country,originalName,originalCode,finalCode,vernacName,...,removalFactorAGCBGCMgHaYr,removalFactorAGCBGCstdevMgHaYr,removalFactorAGCMgHaYr,removalFactorAGCstdevMgHaYr,removalFactorSource,removalFactorStdevSource,removalFactorNotes,removalFactorSourceRegion,plantedYear,geometry
32901,BRA_19,0.034529,0.000057,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,2011.0,"MULTIPOLYGON (((-59.24957 -9.44021, -59.24914 ..."
32902,BRA_19,0.020994,0.000019,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,2014.0,"MULTIPOLYGON (((-59.25392 -9.44592, -59.25376 ..."
32903,BRA_19,0.129054,0.000226,BRA,BR,Brazil,"Large industrial plantation, Coffee, transpare...",19,19,Coffee,...,3.67,2.2211,2.96,2.22,IPCC 2019 Refinement Cropland Table 5.2,Standard deviation calculated from uncertainty...,South America tropical wet shaded perennial de...,South America - tropical wet,2005.0,"MULTIPOLYGON (((-56.34605 -10.12426, -56.34775..."

In [28]:
for i, gdf in enumerate([amazon_coffee, rest]):

    
    # Determine the bounds of your GeoDataFrame
    minx, miny, maxx, maxy = gdf.total_bounds

    # Set your desired resolution
    #resolution = 10  # in meters
    resolution = 0.0001 #in degrees

    # Calculate the dimensions of the raster
    width = int((maxx - minx) / resolution)
    height = int((maxy - miny) / resolution)

    # Create the raster's transform
    transform = from_origin(minx, maxy, resolution, resolution)

    # Create the destination raster's profile
    profile = {
        'driver': 'GTiff',
        'height': height,
        'width': width,
        'count': 1,
        'dtype': rasterio.uint8,
        'crs': gdf.crs,
        'transform': transform,
        'nodata': 0
    }

    # Convert the GeoDataFrame's geometry to the format required by rasterize()
    shapes = [(geom, 1) for geom in gdf.geometry]  # Change 1 to another value if needed

    # Rasterize the shapes
    rasterized = rasterize(shapes, out_shape=(height, width), transform=transform,
                           fill=0, all_touched=True, dtype='uint8')

    ## Save the rasterized shapes to a new file
    with rasterio.open(f"../data/input_datasets/sdpt_coffee_brazil/{i}.tif", 'w', **profile) as dst:
        dst.write(rasterized, 1)